import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Modal from '../components/Modal'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='bg-gray-50 h-screen overflow-y-scroll scrollbar-hide'>
      <Head>
        <title>Instagram Clone Daniel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/danielprofilephoto-min.jpeg" />
      </Head>

      {/* header */}
      <Header />
      {/* feed  */}
      <Feed />
      {/* modal */}
      <Modal />
    </div>
  )
}
